<?php
/**
 * @version    1-1-0-0 // Y-m-d 2017-03-08
 * @author     HR IT-Solutions Florian Häusler https://www.hr-it-solutions.com
 * @copyright  Copyright (C) 2011 - 2017 Didldu e.K. | HR IT-Solutions
 * @license    http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
**/

defined('_JEXEC') or die;

/**
 * Class DD_GMaps_LocationsTableLocation
 *
 * @since  Version  1.1.0.0
 */
class DD_GMaps_LocationsTableLocation extends JTable
{

	/**
	 * DD_GMaps_LocationsTableLocation constructor.
	 *
	 * @param   JDatabaseDriver  &$db  Database connector object
	 *
	 * @since  Version  1.1.0.0
	 */
	public function __construct(&$db)
	{
		parent::__construct('#__dd_gmaps_locations', 'id', $db);
	}

	public function bind($src, $ignore = array())
	{
		return parent::bind($src, $ignore); // TODO: Change the autogenerated stub
	}


	public function store($updateNulls = false)
	{
		return parent::store($updateNulls); // TODO: Change the autogenerated stub
	}

}